#!/usr/bin/with-contenv bash

# Flush all directory caches
kill -s SIGHUP $(pidof rclone)

# umount fuse fs
mountpoint=$(mount -t fuse.rclone | cut -d" " -f3)
if [ ! -z ${mountpoint} ]; then
    echo unmounting ${mountpoint}
    fusermount -u ${mountpoint}
fi
